title: Mood board
hero_image: images/banner.png
description: Create a mood board webpage for a real or imaginary project.
meta_title: Make your own webpage | Learn web development | Mood board
meta_description: >-
  Make your own webpage and learn web development with the Raspberry Pi
  Foundation. Use HTML and CSS to create a mood board for a real or imaginary
  project.
version: 4
listed: true
copyedit: true
last_tested: '2021-03-26'
steps:
  - title: Introduction
  - title: Design your mood board
  - title: Choose a layout for your mood board
    completion: engaged
  - title: Add your content
  - title: Add style
    completion: internal
  - title: Reflection
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion: external
  - title: Upgrade your project
  - title: Share
